name: "Dependabot Automerge"

on:
  pull_request:

jobs:
  worker:
    runs-on: ubuntu-latest

    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1
      - name: Automerge
        uses: actions/github-script@0.2.0
        if: ${{steps.dependabot-metadata.outputs.update-type == 'version-update:semver-patch'}}
        with:
          script: |
            github.pullRequests.createReview({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE'
            })
            github.pullRequests.merge({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number
            })
          github-token: ${{github.token}}
